apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "microkubes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.microkubes.authorizationserver.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "microkubes.authorizationserver.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  config.json: |
    {
      "serverName": "{{ .Values.microkubes.authorizationserver.name }}",
      "security": {
        "keys": {
          "default": "{{ .Values.microkubes.authorizationserver.security.keys.default }}",
          "system": "{{ .Values.microkubes.authorizationserver.security.keys.system }}"
        },
        "signingMethod": "{{ .Values.microkubes.authorizationserver.security.signingMethod }}",
        "issuer": "{{ .Values.microkubes.authorizationserver.security.issuer }}"
      },
      "microservice": {
        "name": "{{ .Values.microkubes.authorizationserver.microservice.name }}",
        "port": {{ .Values.microkubes.authorizationserver.microservice.port }},
        "paths": [{{- range $index, $item := .Values.microkubes.authorizationserver.microservice.paths }}{{ if $index }}, {{ end }}{{ $item | quote }}{{- end }}],
        "virtual_host": "{{ .Values.microkubes.authorizationserver.name }}.service.consul",
        "weight": {{ .Values.microkubes.authorizationserver.microservice.weight }},
        "slots": {{ .Values.microkubes.authorizationserver.microservice.slots }}
      },
      "services": {
        "userServiceURL": "http://{{ .Release.Name }}-{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}/users",
        "appsServiceURL": "http://{{ .Release.Name }}-{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}/apps"
      },
      "database": {
        "host": "{{ .Release.Name }}-{{ .Values.mongodb.service.name }}:27017",
        "database": "{{ .Values.microkubes.authorizationserver.database.name }}",
        "user": "{{ .Values.microkubes.authorizationserver.database.user }}",
        "pass": "{{ .Values.microkubes.authorizationserver.database.pass }}"
      },
      "session": {
        "name": "{{ .Values.microkubes.authorizationserver.session.name }}",
        "authKey": "{{ .Values.microkubes.authKey }}",
        "encryptKey": "{{ .Values.microkubes.encryptKey }}"
      },
      "clientAuthorizationTTL": {{ .Values.microkubes.authorizationserver.clientAuthorizationTTL }},
      "accessTokenTTL": 2592000000,
      "accessTokenSigningMethod": "{{ .Values.microkubes.authorizationserver.accessTokenSigningMethod }}",
      "authCodeLength": {{ .Values.microkubes.authorizationserver.authCodeLength }},
      "refreshTokenLength": {{ .Values.microkubes.authorizationserver.refreshTokenLength }}
    }
