apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "microkubes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.microkubes.authorizationserver.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "microkubes.authorizationserver.fullname" . }}
data:
  config.json: |
    {
      "serverName": "Microkubes Authorization Server",
      "security": {
        "keys": {
          "default": "/run/secrets/default",
          "system": "/run/secrets/system"
        },
        "signingMethod": "RS256",
        "issuer": "oauth2-auth-server"
      },
      "microservice": {
        "name": "oauth2-auth-server",
        "port": 8080,
        "paths": [ "/oauth2", "/auth" ],
        "virtual_host": "{{ .Values.microkubes.authorizationserver.name }}.service.consul",
        "weight": 10,
        "slots": 10
      },
      "services": {
        "userServiceURL": "http://{{ .Values.kong.name }}:8000/users",
        "appsServiceURL": "http://{{ .Values.kong.name }}:8000/apps"
      },
      "database": {
        "host": "{{ .Values.mongodb.name }}:27017",
        "database": "oauth2",
        "user": "authserver",
        "pass": "authserver"
      },
      "session": {
        "name": "OAuth2Server",
        "authKey": "{{ .Values.microkubes.authKey }}",
        "encryptKey": "{{ .Values.microkubes.encryptKey }}"
      },
      "clientAuthorizationTTL": 300000,
      "accessTokenTTL": 2592000000,
      "accessTokenSigningMethod": "RS256",
      "authCodeLength": 10,
      "refreshTokenLength": 27
    }
