apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "microkubes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.microkubes.identityprovider.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "microkubes.identityprovider.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  config.json: |
    {
      "microservice":	{
        "name": "{{ .Values.microkubes.identityprovider.name }}",
        "port": {{ .Values.microkubes.identityprovider.microservice.port }},
        "paths": [{{- range $index, $item := .Values.microkubes.identityprovider.microservice.paths }}{{ if $index }}, {{ end }}{{ $item | quote }}{{- end }}],
        "virtual_host": "{{ .Values.microkubes.identityprovider.name }}.service.consul",
        "weight": {{ .Values.microkubes.identityprovider.microservice.weight }},
        "slots": {{ .Values.microkubes.identityprovider.microservice.slots }}
      },
      "gatewayUrl": "http://{{ .Release.Name }}-{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}",
      "gatewayAdminUrl": "http://{{ .Release.Name }}-{{ .Values.kong.adminServiceName }}:{{ .Values.kong.adminServicePort }}",
      "systemKey": {{ .Values.microkubes.identityprovider.systemKey | quote }},
      "services": {
        "microservice-user": "http://{{ .Release.Name }}-{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}/users"
      },
      "client": {
        "redirect-from-login": "https://{{ .Release.Name }}-{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}/profiles/me"
      },
      "database":{
          "dbName": "{{ .Values.microkubes.database }}",
          "dbInfo": {
          "credentials": "{{ .Values.microkubes.awsDatabaseCredentials }}",
          "endpoint": "{{ .Values.microkubes.awsDatabaseEndpoint }}",
          "awsRegion": "{{ .Values.microkubes.aswDatabaseRegion }}",
          "host": "{{ .Release.Name }}-{{ .Values.mongodb.service.name }}:27017",
          "database": "{{ .Values.microkubes.identityprovider.database.name }}",
          "user": "{{ .Values.microkubes.identityprovider.database.user }}",
          "pass": "{{ .Values.microkubes.identityprovider.database.pass }}"
          }
      }
    }
