apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "microkubes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.microkubes.jwtissuer.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "microkubes.jwtissuer.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  config.json: |
    {
      "jwt":{
        "issuer": "Microkubes JWT Authority",
        "signingMethod": "RS512",
        "expiryTime": 86400000
      },
      "keys": {
        "default": "/run/secrets/default",
        "system": "/run/secrets/system"
      },
      "microservice": {
        "name": "{{ .Values.microkubes.jwtissuer.name }}",
        "port": 8080,
        "paths": ["/jwt"],
        "virtual_host": "{{ .Values.microkubes.jwtissuer.name }}.service.consul",
        "weight": 10,
        "slots": 100
      },
      "services": {
        "user-microservice": "http://{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}/users"
      }
    }