apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "microkubes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.microkubes.jwtissuer.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "microkubes.jwtissuer.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  config.json: |
    {
      "jwt":{
        "issuer": "{{ .Values.microkubes.jwtissuer.jwt.issuer }}",
        "signingMethod": "{{ .Values.microkubes.jwtissuer.jwt.signingMethod }}",
        "expiryTime": 86400000
      },
      "keys": {
        "default": {{ .Values.microkubes.jwtissuer.keys.default | quote }},
        "system": {{ .Values.microkubes.jwtissuer.keys.system | quote }}
      },
      "microservice": {
        "name": "{{ .Values.microkubes.jwtissuer.name }}",
        "port": {{ .Values.microkubes.jwtissuer.microservice.port }},
        "paths": [{{- range $index, $item := .Values.microkubes.jwtissuer.microservice.paths }}{{ if $index }}, {{ end }}{{ $item | quote }}{{- end }}],
        "virtual_host": "{{ .Values.microkubes.jwtissuer.name }}.service.consul",
        "weight": {{ .Values.microkubes.jwtissuer.microservice.weight }},
        "slots": {{ .Values.microkubes.jwtissuer.microservice.slots }}
      },
      "services": {
        "user-microservice": "http://{{ .Release.Name }}-{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}/users"
      }
    }