apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ template "kong.fullname" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "microkubes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.kong.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.kong.replicas }}
  template:
    metadata:
      name: "{{ template "kong.fullname" . }}"
      labels:
        app: "{{ template "kong.fullname" . }}"
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        component: "{{ .Values.kong.name }}"
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
        platform: microkubes
    spec:
      containers:
      - name: {{ template "microkubes.name" . }}-{{ .Values.kong.name }}
        image: {{ .Values.kong.image.repository }}
        imagePullPolicy: {{ .Values.kong.image.pullPolicy }}
        env:
          - name: KONG_ADMIN_LISTEN
            value: "{{ .Values.kong.env.adminListen }}"
          - name: KONG_PG_HOST
            value: "{{ .Release.Name }}-{{ .Values.postgres.name }}"
          - name: KONG_PG_PASSWORD
            value: "{{ .Values.kong.env.PGPassword }}"
          - name: KONG_PROXY_ACCESS_LOG
            value: "{{ .Values.kong.env.proxyAccessLog }}"
          - name: KONG_ADMIN_ACCESS_LOG
            value: "{{ .Values.kong.env.adminAccessLog }}"
          - name: KONG_PROXY_ERROR_LOG
            value: "{{ .Values.kong.env.proxyErrorLog }}"
          - name: KONG_ADMIN_ERROR_LOG
            value: "{{ .Values.kong.env.adminErrorLog }}"
          - name: KONG_DNS_SERVER_NAME
            value: "{{ .Release.Name }}-{{ .Values.consul.name }}"
          - name: KONG_DNS_SERVER_PORT
            value: "{{ .Values.kong.env.dnsServerPort }}"
          - name: CONSUL_URL
            value: "{{ template "consul.URL" . }}"
        ports:
        - name: admin
          containerPort: {{ .Values.kong.adminServicePort }}
          protocol: {{ .Values.kong.adminServiceProtocol }}
        - name: proxy
          containerPort: {{ .Values.kong.servicePort }}
          protocol: {{ .Values.kong.serviceProtocol }}