apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.kong.name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "microkubes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.kong.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.kong.serviceType }}
  ports:
  - name: proxy
    port: {{ .Values.kong.servicePort }}
    targetPort: {{ .Values.kong.servicePort }}
    protocol: {{ .Values.kong.serviceProtocol }}
  selector:
    app: "{{ template "kong.fullname" . }}"