apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.kong.adminServiceName }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "microkubes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.kong.adminServiceName }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.kong.adminServiceType }}
  ports:
  - name: admin
    port: {{ .Values.kong.adminServicePort }}
    targetPort: {{ .Values.kong.adminServicePort }}
    protocol: {{ .Values.kong.adminServiceProtocol }}
  selector:
    app: "{{ template "kong.fullname" . }}"