apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "microkubes.microservicemail.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "microkubes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.microkubes.microservicemail.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  config.json: |
    {
      "verificationURL": "http://{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}/users/verify",
      "mail": {
        "host": "{{ .Values.mailconfig.host }}",
        "port": "{{ .Values.mailconfig.port }}",
        "user": "{{ .Values.mailconfig.user }}",
        "password": "{{ .Values.mailconfig.password }}",
        "email": "{{ .Values.mailconfig.email }}"
      },
      "rabbitmq": {
        "username": "{{ .Values.rabbitmq.username }}",
        "password": "{{ .Values.rabbitmq.password }}",
        "host": "{{ .Values.rabbitmq.host }}",
        "port": "{{ .Values.rabbitmq.port }}"
      }
    }
