apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.secrets.mongoDB.name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "microkubes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: "{{ .Values.secrets.mongoDB.type }}"
data:
  create_microkubes_db_objects.sh: "{{ .Values.secrets.mongoDB.data.createMicrokubesDBObjects }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.secrets.keys.name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "microkubes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: "{{ .Values.secrets.keys.type }}"
data:
  default: "{{ .Values.secrets.keys.data.default }}"
  default.pub: "{{ .Values.secrets.keys.data.defaultPub }}"
  private.pem: "{{ .Values.secrets.keys.data.privatePem }}"
  public.pub: "{{ .Values.secrets.keys.data.publicPub }}"
  service.cert: "{{ .Values.secrets.keys.data.serviceCert }}"
  service.key: "{{ .Values.secrets.keys.data.serviceKey }}"
  system: "{{ .Values.secrets.keys.data.system }}"
  system.pub: "{{ .Values.secrets.keys.data.systemPub }}"