apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "microkubes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.microkubes.user.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "microkubes.user.fullname" . }}
  namespace: microkubes
data:
  config.json: |
    {
      "service": {
        "name": "{{ .Values.microkubes.user.name }}",
        "port": 8080,
        "paths": [
          "/users"
        ],
        "virtual_host": "{{ .Values.microkubes.user.name }}.service.consul",
        "weight": 10,
        "slots": 100
      },
      "gatewayUrl": "http://{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}",
      "gatewayAdminUrl": "http://{{ .Values.kong.adminServiceName }}:{{ .Values.kong.adminServicePort }}",
      "security": {
        "keysDir": "/run/secrets",
        "ignorePatterns": [
          "/users/verify"
        ],
        "jwt": {
          "name": "JWTSecurity",
          "description": "JWT security middleware",
          "tokenUrl": "http://{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}/jwt"
        },
        "saml": {
          "certFile": "/run/secrets/service.cert",
          "keyFile": "/run/secrets/service.key",
          "identityProviderUrl": "http://{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}/saml/idp",
          "userServiceUrl": "http://{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}/users",
          "registrationServiceUrl": "http://{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}/users/register",
          "rootURL": "http://localhost:{{ .Values.kong.servicePort }}/users"
        },
        "oauth2": {
          "description": "OAuth2 security middleware",
          "tokenUrl": "https://{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}/oauth2/token",
          "authorizeUrl": "https://{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}/oauth2/authorize"
        },
        "acl": {
          "policies": [
            {
              "id": "users-allow-admin-access",
              "description": "Allows access to everything to an admin user",
              "resources": [
                "<.+>"
              ],
              "actions": [
                "api:read",
                "api:write"
              ],
              "effect": "allow",
              "subjects": [
                "<.+>"
              ],
              "conditions": {
                "roles": {
                  "type": "RolesCondition",
                  "options": {
                    "values": [
                      "admin",
                      "system"
                    ]
                  }
                }
              }
            },
            {
              "id": "users-allow-read-access",
              "description": "Allows access to user's own profile",
              "resources": [
                "/users/me"
              ],
              "actions": [
                "api:read"
              ],
              "effect": "allow",
              "subjects": [
                "<.+>"
              ],
              "conditions": {
                "roles": {
                  "type": "RolesCondition",
                  "options": {
                    "values": [
                      "user"
                    ]
                  }
                }
              }
            },
            {
              "id": "read-swagger",
              "description": "Allows to service swagger.",
              "resources": [
                "/swagger<.+>"
              ],
              "actions": [
                "api:read"
              ],
              "effect": "allow",
              "subjects": [
                "<.+>"
              ]
            }
          ]
        }
      },
      "database":{
        "dbName": "{{ .Values.microkubes.database }}",
        "dbInfo": {
          "credentials": "{{ .Values.microkubes.awsDatabaseCredentials }}",
          "endpoint": "{{ .Values.microkubes.awsDatabaseEndpoint }}",
          "awsRegion": "{{ .Values.microkubes.aswDatabaseRegion }}",
          "host": "{{ .Values.mongodb.service.name }}:27017",
          "database": "users",
          "user": "restapi",
          "pass": "restapi"
        }
      }
    }