apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "microkubes.userprofile.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "microkubes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.microkubes.userprofile.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  config.json: |
    {
      "service":{
        "name": "{{ .Values.microkubes.userprofile.name }}",
        "port": 8080,
        "paths": ["/profiles"],
        "virtual_host": "{{ .Values.microkubes.userprofile.name }}.service.consul",
        "weight": 10,
        "slots": 100
      },
      "gatewayUrl": "http://{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}",
      "gatewayAdminUrl": "http://{{ .Values.kong.adminServiceName }}:{{ .Values.kong.adminServicePort }}",
      "security":{
        "keysDir": "/run/secrets",
        "jwt":{
          "description": "JWT security middleware",
          "tokenUrl": "http://{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}/jwt/signin"
        },
        "saml":{
          "certFile": "/run/secrets/service.cert",
          "keyFile": "/run/secrets/service.key",
          "identityProviderUrl": "http://{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}/saml/idp",
          "userServiceUrl": "http://{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}/users",
          "registrationServiceUrl": "http://{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}/users/register",
          "rootURL": "http://localhost:{{ .Values.kong.servicePort }}/profiles"
        },
        "oauth2":{
          "description": "OAuth2 security middleware",
          "tokenUrl": "https://{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}/oauth2/token",
          "authorizeUrl": "https://{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}/oauth2/authorize"
        },
        "acl": {
          "policies":[{
              "id": "read-swagger",
              "description": "Allows to service swagger.",
              "resources": ["/swagger<.+>"],
              "actions": ["api:read"],
              "effect": "allow",
              "subjects": ["<.+>"]
          },{
              "id": "profile-allow-admin-access",
              "description": "Allows access to everything to an admin user",
              "resources": ["<.+>"],
              "actions": ["api:read","api:write"],
              "effect": "allow",
              "subjects": ["<.+>"],
              "conditions": {
                "roles": {
                  "type": "RolesCondition",
                  "options": {
                    "values": ["admin"]
                  }
                }
              }
          },{
              "id": "profile-allow-user-access",
              "description": "Allows user to access its profile",
              "resources": ["/profiles/me"],
              "actions": ["api:read","api:write"],
              "effect": "allow",
              "subjects": ["<.+>"]
            }]
        }
      },
      "database":{
        "dbName": "{{ .Values.microkubes.database }}",
        "dbInfo": {
          "credentials": "{{ .Values.microkubes.awsDatabaseCredentials }}",
          "endpoint": "{{ .Values.microkubes.awsDatabaseEndpoint }}",
          "awsRegion": "{{ .Values.microkubes.aswDatabaseRegion }}",
          "host": "{{ .Values.mongodb.service.name }}:27017",
          "database": "user-profiles",
          "user": "restapi",
          "pass": "restapi"
        }
      }
    }
