apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "microkubes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    platform: microkubes
  name: {{ .Values.microkubes.serviceAccountName }}
