apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: microkubes-clusterrolebinding
  labels:
    platform: microkubes
subjects:
- kind: ServiceAccount
  name: {{ .Values.microkubes.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
