apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "microkubes.appsmanagement.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "microkubes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.microkubes.appsmanagement.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  config.json: |
    {
      "service":{
        "name": "{{ .Values.microkubes.appsmanagement.name }}",
        "port": {{ .Values.microkubes.appsmanagement.service.port }},
        "paths": [{{- range $index, $item := .Values.microkubes.appsmanagement.service.paths }}{{ if $index }}, {{ end }}{{ $item | quote }}{{- end }}],
        "virtual_host": "{{ .Values.microkubes.appsmanagement.name }}.service.consul",
        "weight": {{ .Values.microkubes.appsmanagement.service.weight }},
        "slots": {{ .Values.microkubes.appsmanagement.service.port }}
      },
      "gatewayUrl": "http://{{ .Release.Name }}-{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}",
      "security":{
        "keysDir": {{ .Values.microkubes.appsmanagement.security.keysDir | quote }},
        "jwt":{
          "description": "{{ .Values.microkubes.appsmanagement.security.jwt.description }}",
          "tokenUrl": "http://{{ .Release.Name }}-{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}/jwt/signin"
        },
        "saml":{
          "certFile": {{ .Values.microkubes.appsmanagement.security.saml.certFile | quote }},
          "keyFile": {{ .Values.microkubes.appsmanagement.security.saml.keyFile | quote }},
          "identityProviderUrl": "http://{{ .Release.Name }}-{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}/saml/idp",
          "userServiceUrl": "http://{{ .Release.Name }}-{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}/users",
          "registrationServiceUrl": "http://{{ .Release.Name }}-{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}/users/register",
          "rootURL": "http://{{ .Release.Name }}-{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}/apps"
        },
        "oauth2":{
          "description": "{{ .Values.microkubes.appsmanagement.security.oauth2.description }}",
          "tokenUrl": "https://{{ .Release.Name }}-{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}/oauth2/token",
          "authorizeUrl": "https://{{ .Release.Name }}-{{ .Values.kong.name }}:{{ .Values.kong.servicePort }}/oauth2/authorize"
        },
        "acl": {
          "policies":[{
              "id": "{{ .Values.microkubes.appsmanagement.security.acl.policy_swagger.id }}",
              "description": "{{ .Values.microkubes.appsmanagement.security.acl.policy_swagger.description }}",
              "resources": [{{- range $index, $item := .Values.microkubes.appsmanagement.security.acl.policy_swagger.resources }}{{ if $index }}, {{ end }}{{ $item | quote }}{{- end }}],
              "actions": [{{- range $index, $item := .Values.microkubes.appsmanagement.security.acl.policy_swagger.actions }}{{ if $index }}, {{ end }}{{ $item | quote }}{{- end }}],
              "effect": "{{ .Values.microkubes.appsmanagement.security.acl.policy_swagger.effect }}",
              "subjects": [{{- range $index, $item := .Values.microkubes.appsmanagement.security.acl.policy_swagger.subjects }}{{ if $index }}, {{ end }}{{ $item | quote }}{{- end }}]
          },{
              "id": "{{ .Values.microkubes.appsmanagement.security.acl.policy_admin.id }}",
              "description": "{{ .Values.microkubes.appsmanagement.security.acl.policy_admin.description }}",
              "resources": [{{- range $index, $item := .Values.microkubes.appsmanagement.security.acl.policy_admin.resources }}{{ if $index }}, {{ end }}{{ $item | quote }}{{- end }}],
              "actions": [{{- range $index, $item := .Values.microkubes.appsmanagement.security.acl.policy_admin.actions }}{{ if $index }}, {{ end }}{{ $item | quote }}{{- end }}],
              "effect": "{{ .Values.microkubes.appsmanagement.security.acl.policy_admin.effect }}",
              "subjects": [{{- range $index, $item := .Values.microkubes.appsmanagement.security.acl.policy_admin.subjects }}{{ if $index }}, {{ end }}{{ $item | quote }}{{- end }}],
              "conditions": {
                "roles": {
                  "type": "{{ .Values.microkubes.appsmanagement.security.acl.policy_admin.conditions.roles.type }}",
                  "options": {
                    "values": [{{- range $index, $item := .Values.microkubes.appsmanagement.security.acl.policy_admin.conditions.roles.options.values }}{{ if $index }}, {{ end }}{{ $item | quote }}{{- end }}]
                  }
                }
              }
          },{
              "id": "{{ .Values.microkubes.appsmanagement.security.acl.policy_user.id }}",
              "description": "{{ .Values.microkubes.appsmanagement.security.acl.policy_user.description }}",
              "resources": [{{- range $index, $item := .Values.microkubes.appsmanagement.security.acl.policy_user.resources }}{{ if $index }}, {{ end }}{{ $item | quote }}{{- end }}],
              "actions": [{{- range $index, $item := .Values.microkubes.appsmanagement.security.acl.policy_user.actions }}{{ if $index }}, {{ end }}{{ $item | quote }}{{- end }}],
              "effect": "{{ .Values.microkubes.appsmanagement.security.acl.policy_user.effect }}",
              "subjects": [{{- range $index, $item := .Values.microkubes.appsmanagement.security.acl.policy_user.subjects }}{{ if $index }}, {{ end }}{{ $item | quote }}{{- end }}]
            }]
        }
      },
      "database":{
        "dbName": "{{ .Values.microkubes.database }}",
        "dbInfo": {
          "credentials": "{{ .Values.microkubes.awsDatabaseCredentials }}",
          "endpoint": "{{ .Values.microkubes.awsDatabaseEndpoint }}",
          "awsRegion": "{{ .Values.microkubes.aswDatabaseRegion }}",
          "host": "{{ .Release.Name }}-{{ .Values.mongodb.service.name }}:27017",
          "database": "{{ .Values.microkubes.appsmanagement.database.dbInfo.database }}",
          "user": "{{ .Values.microkubes.appsmanagement.database.dbInfo.user }}",
          "pass": "{{ .Values.microkubes.appsmanagement.database.dbInfo.pass }}"
        }
      }
    }
    