apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.microkubes.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "microkubes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    platform: microkubes