apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "microkubes.microservicemail.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "microkubes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.microkubes.microservicemail.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  config.json: |
    {
      "templatesBaseLocation": "{{ .Values.mailtemplates.baseLocation }}",
      "templates": {
        "userVerification": {
          "filename" : "{{ .Values.mailtemplates.userVerification.filename }}",
          "subject": "{{ .Values.mailtemplates.userVerification.subject }}",
          "data": {
            "url": "{{ .Values.mailtemplates.userVerification.data.url }}"
          }
        },
        "forgotPassword": {
          "filename" : "{{ .Values.mailtemplates.forgotPassword.filename }}",
          "subject": "{{ .Values.mailtemplates.forgotPassword.subject }}",
          "data": {
            "url": "{{ .Values.mailtemplates.forgotPassword.data.url }}"
          }
        }
      },
      "mail": {
        "host": "{{ template "mailconfig.host" . }}",
        "port": "{{ .Values.mailconfig.port }}",
        "user": "{{ .Values.mailconfig.user }}",
        "password": "{{ .Values.mailconfig.password }}",
        "email": "{{ .Values.mailconfig.email }}"
      },
      "amqpConfig": {
        "username": "{{ .Values.rabbitmq.username }}",
        "password": "{{ .Values.rabbitmq.password }}",
        "host": "{{ .Release.Name }}-{{ .Values.rabbitmq.service.name }}",
        "port": "{{ .Values.rabbitmq.port }}"
      }
    }
