dependencies:
  - name: consul
    version: 3.3.0
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: postgresql
    version: 0.15.1
    repository: https://kubernetes-charts.storage.googleapis.com/
