# Default values for microkubes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
microkubes:
  # Global platform coniguration
  # Database to use: mongodb or aws (dynamodb)
  database: mongodb
  awsDatabaseCredentials: /full/path/to/aws/credentials
  awsDatabaseEndpoint: http://localhost:9000
  awsDatabaseRegion: us-east-1

  serviceAccountName: microkubes
  kongAdminUrl: http://kong-admin:8001

  authKey: dGVzdC1hdXRoLWtleQo=
  encryptKey: t/xzB8eZ5ypUiIGbuOq5PhZAKpU7LS239ucRXDq7Lw8=

  # Microkubes component configuration
  #
  # Authorization Server
  authorizationserver:
    name: authorization-server

    image:
      repository: microkubes/authorization-server
      tag: latest
      pullPolicy: Always

    podAnnotations:  
      consul.register/enabled: "true"
      consul.register/service.name: "authorization-server"

  # Identity Provider
  identityprovider:
    name: identity-provider

  # JWT Issuer
  jwtissuer:
    name: jwt-issuer

  # Apps Management
  appsmanagement:
    name: apps-management

  # Mail
  mail:
    name: microservice-mail

  # Microservice Registration
  microserviceregistration:
    name: microservice-registration

  # User
  user:
    name: microservice-user

  # User Profile
  userprofile:
    name: microservice-profile

# Microkubes database configuration
# Mongo
mongodb:
  name: mongo
# API Gateway configuration
# KONG
kong:
  name: kong
  servicePort: 8000
  adminServiceName: kong-admin
  adminServicePort: 8001

# Service Discovery configuration
# CONSUL
consul:
  option1: value

# Kubernetes consul auto registration
# Kube-consul-register
kubeconsulregister:
  option1: value

# RabbitMQ
rabbitmq:
  option1: value

# END CONFIGURATION

replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
