apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-consul-register
  namespace: microkubes
  labels:
    platform: microkubes
data:
  consul_address: "consul"
  consul_port: "8500"
  consul_scheme: "http"
  consul_ca_file: ""
  consul_cert_file: ""
  consul_key_file: ""
  consul_insecure_skip_verify: "false"
  consul_token: ""
  consul_timeout: "2s"
  consul_container_name: "consul"
  consul_node_selector: "consul=enabled"
  pod_label_selector: ""
  k8s_tag: "microkubes"
  register_mode: "single"
  register_source: "pod"

---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: kube-consul-register
  namespace: microkubes
  labels:
    platform: microkubes
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-consul-register
        platform: microkubes
    spec:
      serviceAccountName: microkubes
      containers:
      - name: kube-consul-register
        image: tczekajlo/kube-consul-register:0.1.6
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 1
            memory: 300Mi
        args:
        - -logtostderr=true
        - -configmap=default/kube-consul-register
