apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: microkubes
  labels:
    platform: microkubes
spec:
  ports:
  - name: rabbitmq
    port: 5672
    targetPort: 5672
    protocol: TCP
  - name: rabbitmq-ui
    port: 15672
    targetPort: 15672
    protocol: TCP
  selector:
    app: rabbitmq

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: microkubes
  labels:
    platform: microkubes
spec:
  serviceName: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.7.7-management
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: guest
            - name: RABBITMQ_DEFAULT_PASS
              value: guest
          ports:
            - name: rabbitmq
              containerPort: 5672
            - name: rabbitmq-ui
              containerPort: 15672
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-data
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
