apiVersion: v1
kind: ServiceAccount
metadata:
  name: microkubes
  namespace: microkubes
  labels:
    platform: microkubes

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: microkubes-clusterrolebinding
  labels:
    platform: microkubes
subjects:
- kind: ServiceAccount
  name: microkubes
  namespace: microkubes
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
